name: Build-Test-Deploy Node App

on:
  push:
    branches:
      - main # Runs when pushing to main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.1.0"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest

      - name: Deploy to Netlify
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --auth ${{ secrets.NETLIFY_API_KEY }} --dir=dist